name: Deploy
on:
  push:
    branches: [main, staging]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
      deployment: true
      url: ${{ vars.PUBLIC_URL }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Clean up previous cache
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: 22
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: rm -rf ~/deploy_cache

      - name: Rsync to server
        uses: burnett01/rsync-deployments@155b6d6c1219ab2224c20c58d423a3f1b850395f # v9
        with:
          switches: -avzr --delete --exclude=/.git/ --exclude=/.github/
          path: .
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_path: ${{ secrets.REMOTE_ROOT }}/deploy_cache

      - name: Replace served directory with cache
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: 22
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            mv ~/public_html ~/.delete_me
            cp -r ~/deploy_cache ~/public_html
            rm -rf ~/.delete_me
